{{- if eq .Values.deploymentType "deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mattermost-rtcd.fullname" . }}
  labels:
    {{- include "mattermost-rtcd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.configuration.replicas }}
  selector:
    matchLabels:
      {{- include "mattermost-rtcd.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if eq .Values.configuration.updateStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.configuration.maxUnavailable }}
    {{- end }}
    type: {{ .Values.configuration.updateStrategy }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mattermost-rtcd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.configuration.hostNetwork }}
      hostNetwork: true
      {{- end }}
      serviceAccountName: {{ include "mattermost-rtcd.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.configuration.terminationGracePeriod }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.configuration.environmentVariables }}
          env:
            {{- range $key, $val := .Values.configuration.environmentVariables }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end}}
          {{- end }}
          {{- if .Values.configuration.extraVolumeMounts }}
          volumeMounts: {{ toYaml .Values.configuration.extraVolumeMounts | nindent 12 }}
          {{- end }}
          ports:
            - name: api
              containerPort: {{ .Values.service.APIport }}
              hostPort: {{ .Values.service.APIport }}
              protocol: TCP              
            - name: rtc-udp
              containerPort: {{ .Values.service.RTCport }}
              hostPort: {{ .Values.service.RTCport }}
              protocol: UDP
            - name: rtc-tcp
              containerPort: {{ .Values.service.RTCport }}
              hostPort: {{ .Values.service.RTCport }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /version
              port: api
            initialDelaySeconds: {{ .Values.configuration.livenessProbeInitialDelaySeconds | default 30 }}
            failureThreshold: {{ .Values.configuration.livenessProbeFailureThreshold | default 3 }}
            periodSeconds: {{ .Values.configuration.livenessProbePeriodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.configuration.livenessProbeTimeoutSeconds | default 5 }}
          readinessProbe:
            httpGet:
              path: /version
              port: api
            initialDelaySeconds: {{ .Values.configuration.readinessProbeInitialDelaySeconds | default 30 }}
            failureThreshold: {{ .Values.configuration.readinessProbeFailureThreshold | default 3 }}
            periodSeconds: {{ .Values.configuration.readinessProbePeriodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.configuration.readinessProbeTimeoutSeconds | default 5 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configuration.extraVolumes }}
      volumes: {{ toYaml .Values.configuration.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}
