apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-push-config-template
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-push-proxy.chart" . }}
data:
  push-config.tpl: |
{{include "push-config.tpl" . | printf "%s" | indent 4}}
