{{- if not .Values.global.features.database.existingDatabaseSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost.fullname" . }}-mattermost-dbsecret
  labels:
    app.kubernetes.io/name: {{ include "mattermost.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "mattermost.chart" . }}
type: Opaque
data:
  mattermost.dbsecret: {{ .Values.global.features.database.dataSource | b64enc }}
{{- end }}