{{- if not .Values.global.existingLicenseSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost.fullname" . }}-mattermost-license
  labels:
    app.kubernetes.io/name: {{ include "mattermost.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "mattermost.chart" . }}
type: Opaque
data:
  mattermost.mattermost-license: {{ .Values.global.mattermostLicense | b64enc | quote  }}
{{- end -}}