apiVersion: v2
name: mattermost-operator
description: A Helm chart for Mattermost Operator
type: application
version: 0.2.2
appVersion: 1.16.0
keywords:
- operator
- mattermost
maintainers:
  - name: stylianosrigas
