apiVersion: v2
name: mattermost-operator
description: A Helm chart for Mattermost Operator
type: application
version: 1.0.1
appVersion: 1.21.0
keywords:
- mattermost
- operator
maintainers:
  - name: stylianosrigas
  - name: gabrieljackson
sources:
- https://github.com/mattermost/mattermost-helm/tree/master/charts/mattermost-operator
