mattermostApp:
  replicaCount: 1
  persistence:
    pluginsServer:
      enabled: false
    pluginsClient:
      enabled: false
    configApp:
      enabled: false

mysqlha:
  mysqlha:
    replicaCount: 1
  persistence:
    enabled: false

minio:
  persistence:
    enabled: false
