mattermostApp:
  replicaCount: 1
  persistence:
    pluginsServer:
      enabled: false
    pluginsClient:
      enabled: false
    configApp:
      enabled: false

  extraInitContainers:
    - name: init-test
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - "-c"
        - |
          echo "Hello Mattermost"
      volumeMounts:
        - mountPath: /tmp/test-tmp
          name: varlog

  extraVolumeMounts:
    - name: varlog
      emptyDir: {}
      readOnly: true

mysqlha:
  mysqlha:
    replicaCount: 1
