{{- if .Values.global.features.jobserver.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mattermost-app.jobserver.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.global.features.jobserver.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-jobserver
        component: "{{ .Values.global.features.jobserver.name }}"
    spec:
      initContainers:
        - name: "init-elasticsearch"
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          command: ["sh", "-c", "until ! {{ .Values.global.features.elasticsearch.enabled }} || curl --max-time 5 http://{{ .Release.Name }}-mattermost-elasticsearch:9200 ; do echo waiting for elasticsearch; sleep 5; done; echo init-elasticsearch finished"]
        - name: "init-mysql"
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          command: ["sh", "-c", "until curl --max-time 5 http://{{ .Release.Name }}-mysqlha-readonly:3306; do echo waiting for {{ .Release.Name }}-mysqlha; sleep 5; done;"]
      containers:
      - name: {{ template "mattermost-app.jobserver.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["platform", "jobserver"]
        volumeMounts:
        - mountPath: /mattermost/config/config.json
          name: config-json
          subPath: config.json
        - mountPath: /mattermost/mattermost.mattermost-license
          name: mattermost-license
          subPath: mattermost.mattermost-license
      volumes:
        - name: config-json
          configMap:
            name: {{template "fullname" .}}-config-json
            items:
            - key: config.json
              path: config.json
        - name: mattermost-license
          secret:
            secretName: {{ .Release.Name }}-mattermost-license
{{- end -}}
