{{- if and .Values.mysqlOperator.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    release: 'mysql-operator'
    app: mysql-operator
  name: mysqlbackups.mysql.presslabs.org
  namespace: mysql-operator
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy" : post-delete 
    "helm.sh/hook-weight": "-4"  
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlBackup
    plural: mysqlbackups
  scope: Namespaced
  version: v1alpha1
{{- end }}