{{- if .Values.mysqlOperator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql-operator.name" . }}-0-svc
  namespace: {{ template "mysql-operator.namespace" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    release: {{ template "mysql-operator.name" . }}
{{- if .Values.mysqlOperator.service.annotations }}
  annotations:
{{ toYaml .Values.mysqlOperator.service.annotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 3000
  - name: raft
    port: 10008
    targetPort: 10008
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "mysql-operator.name" . }}-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql-operator.name" . }}
  namespace: {{ template "mysql-operator.namespace" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    release: {{ template "mysql-operator.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "mysql-operator.name" . }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
{{- end }}
