apiVersion: v2
description: Mattermost Push Proxy server
name: mattermost-push-proxy
type: application
version: 0.13.2
appVersion: 6.2.0
keywords:
  - mattermost
  - communication
  - notification
  - messaging
  - team collaboration
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
maintainers:
  - name: stylianosrigas
    email: stylianos.rigas@mattermost.com
  - name: spirosoik
    email: spiros.economakis@mattermost.com
  - name: delivery-team
    email: devops@mattermost.com
sources:
  - https://github.com/mattermost/mattermost-helm
  - https://github.com/mattermost/mattermost-push-proxy
annotations:
  artifacthub.io/images: |
    - name: mattermost-push-proxy
      image: mattermost/mattermost-push-proxy:6.2.0
  artifacthub.io/license: Apache-2.0
