apiVersion: v1
description: Mattermost Push Proxy server
name: mattermost-push-proxy
version: 0.3.0
appVersion: 5.9.0
keywords:
- mattermost
- communication
- notification
- messaging
- team colaboration
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
maintainers:
  - name: cpanato
    email: carlos@mattermost.com
  - name: jwilander
    email: joram@mattermost.com
source:
- https://github.com/mattermost/mattermost-helm
- https://github.com/mattermost/mattermost-push-proxy
