apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-apple-cert-path
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
   apple-push-cert.pem: {{ .Values.apns.privateCert | quote }}

